### ISSUE TITLE
Proper design for passing options to ESLint

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/beautifier-eslint#2]
Each rule needs to return a severity, and as [described in the docs](https://eslint.org/docs/user-guide/configuring#configuring-rules), 0 means the rule is off and isn't used at all, while 1 and 2 turns the rule into a warning or an error respectfully.  Every rule should by default return 0, and only pass 1 or 2 if a value is being passed for that rule.  Take this for example:

```
      "semi": [
        ["end_with_semicolon"],
        function(options) {
          if (options.end_with_semicolon === true) {
            return [2, "always"]
          } else if (options.end_with_semicolon === false) {
            return [2, "never"];
          }
         return 0;
        }
      ]
```

If the user opts to use the end_with_semicolon rule by choosing true or false, we'll return a 2 with the corresponding value.  If no value is selected, we'll pass a 0 and the rule will not be applied.  Note the severity always needs to come first.

**Comment by Glavin001** [comment]
Unibeautify will not support severity/levels. It should either beautify or not beautify.

**Comment by szeck87** [comment]
Unibeautify doesn't have to, just beautifier-eslint. It needs to return an array like the example above.

**Comment by Glavin001** [comment]
Oh. That's no problem. Is this issue really more so a note to remember for later or something which needs to be discussed? 😛

**Comment by szeck87** [comment]
Mainly just for feedback on this approach based on what's completed thus far.  But also for options that users don't want applied at all.  Take `end_with_comma` for example, users may always want to have a comma or they may not (below respectfully), in which case the beautifier would handle whichever.  But the user may not want the `end_with_comma` option to be applied at all.  So want to make sure that's something Unibeautify will allow (both in a config file and editor options UI).

```
var foo = {
    bar: "baz",
    qux: "quux",
};

var foo = {
    bar: "baz",
    qux: "quux"
};

**Comment by Glavin001** [comment]
For cases like `end_with_comma` I have been implementing the beautifier to use `true`, `false`, and `undefined` (do not apply at all).

**Comment by szeck87** [comment]
Seem to have the pattern down.  Wrote up some explanations in https://github.com/Unibeautify/beautifier-eslint/blob/master/CONTRIBUTING.md

**Comment by Glavin001** [comment]
Awesome work and great docs!
